name = "hw6"
uuid = "44f980ee-618b-4e5f-94d8-c38dcaf837f0"
authors = ["Rom Fradkin <fradkin.rom@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
