name = "HashCode"
uuid = "44f980ee-618b-4e5f-94d8-c38dcaf837f0"
authors = ["Rom Fradkin <fradkin.rom@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
HashCode2014 = "7bbed249-721d-42ac-b1f6-7cf884be0fbe"
Random = "9a3f8284-a2c9-505d-8b9b-7a1cc349470b" 

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
